### ISSUE TITLE
Question about project structure

### ISSUE THREAD

**Issue by toptensoftware** [smuehlst/circle-stdlib#17]
Looking into circle-stdlib for first time and just wondering about how to structure the project.  Seem circle-stdlib includes circle as a git sub-module.  Should I restructure my project to refer to that instead of my current circle repo folder?

**Comment by rsta2** [comment]
Yes, the Circle project is included as a git submodule in libs/circle/. Please have a look at the samples/ subdirectory, where you can find some circle-stdlib specific samples. The project structure of a circle-stdlib application is different from that of a Circle application.
