### ISSUE TITLE
Custom console for stdio?

### ISSUE THREAD

**Issue by toptensoftware** [smuehlst/circle-stdlib#18]
Is it possible to use circle-stdlib with a custom console?  

My circle app, uses OpenGL for screen rendering rather than the default circle screen implementation and will have it's own console implementation.  Can I get circle-stdlib to use it instead?

**Comment by rsta2** [comment]
For a custom console you have to modify the class CStdlibAppStdio in [include/circle_stdlib_app.h](https://github.com/smuehlst/circle-stdlib/blob/master/include/circle_stdlib_app.h#L143). The member mConsole has an additional constructor, which can get pointers to the stdin and stdout devices.
