### ISSUE TITLE
make build-samples wont build on archlinux

### ISSUE THREAD

**Issue by llllllllllbg** [smuehlst/circle-stdlib#29]
> arm-none-eabi-ld: /usr/lib/gcc/arm-none-eabi/12.2.0/../../../../arm-none-eabi/lib/arm/v5te/hard/libstdc++.a(random.o): in function `std::(anonymous namespace)::__libc_getentropy(void*)':
/build/arm-none-eabi-gcc/src/gcc-12.2.0/libstdc++-v3/src/c++11/random.cc:179: undefined reference to `getentropy'

i tried with ./configure --opt-tls --softfp and got the same result. also some of them WILL build.

**Comment by smuehlst** [comment]
Please look at the [README.md](https://github.com/smuehlst/circle-stdlib/blob/master/README.md) where the supported compilers are listed. Apparently you are using a different compiler with a `libstdc++.a` that is not compatible with the version of Newlib that is used in circle-newlib.
