### ISSUE TITLE
Memory stdlib

### ISSUE THREAD

**Issue by koparasy** [smuehlst/circle-stdlib#3]
I need dynamic allocation of data. Should i link my source code with the malloc provided by circle or the malloc provided by libc. 

Thank You

**Comment by smuehlst** [comment]
You can simply use C `malloc()` or C++ `new`, and link your application with `libc.a`, `libcirclenewlib.a` and the Circle libraries, as demonstrated with the applications in the ` samples` subdirectory. The modified newlib version built from subdirectory `libs/circle-newlib` does use Circle's malloc internally, so there's no need to worry about where it comes from.
