### ISSUE TITLE
No output from printf() in samples/02-stdio-hello with v16.3

### ISSUE THREAD

**Issue by swausd** [smuehlst/circle-stdlib#35]
With the current release v16.3 I get no output on hdmi screen from printf() in kernel.cpp, line 36, when running samples/02-stdio-hello. Output from fprintf() from line 37 is ok.
 I get output as expected when using v16.2.

Using Raspi Zero 2 W, gcc 12.2.Rel1, 32 bit.
Am I missing some new configurations with circle step 46?

**Comment by smuehlst** [comment]
Hmm, that is interesting, but I won't be able to look into this before the weekend.

**Comment by smuehlst** [comment]
Reproduced the problem as described with a Raspberry Pi Zero:

* With circle-stdlib [v16.2](https://github.com/smuehlst/circle-stdlib/tree/v16.2)  the sample `02-stdio-hello` produces `stdio` output with `printf()` as expected.
* With circle-stdlib [v16.3](https://github.com/smuehlst/circle-stdlib/tree/v16.3) `stdio` output is missing, while `stderr` output still does appear on the screen.

**Comment by smuehlst** [comment]
Also reproducible with a 64-bit build under QEMU.

**Comment by smuehlst** [comment]
The problem is that `stdout` is for some reason no longer line-buffered. Adding a `fflush(stdout)` after `printf(...)´ makes the text appear on the screen.

**Comment by smuehlst** [comment]
@swausd I committed a fix directly to the master branch and I will create a bugfix release later today. If you want to test the fix, please make sure that you also update the circle-newlib submodule where the fix was actually implemented.

**Comment by swausd** [comment]
Looks OK for me.
Thank you for the super quick fix!
