### ISSUE TITLE
make completes without problem but qemu does not start at all

### ISSUE THREAD

**Issue by Valefungo** [smuehlst/circle-stdlib#40]
Hello,

I have a weird behaviour for my project, it seems that if I link too many C files together, QEMU stops booting kernel8.img

Basically I copied the 02-stdio-hello example, added all my sources to Makefile, modified kernel.cpp to call my "main" within ->Run() and did a full build, all fine except qemu stopped working.
Then started reducing the linked files by stubbing missing functions until I reached a point where it starts again doing what 02-stdio-hello was supposed to do and my main is called within Run and does almost nothing except correctly reading a file.

the QEMU command line is:
./qemu/build/qemu-system-aarch64 -M raspi3b -no-shutdown -action reboot=reset -action shutdown=pause -action panic=pause -action watchdog=pause -kernel circle-stdlib/samples/22-stdio-hello/kernel8.img -global bcm2835-fb.xres=640 -global bcm2835-fb.yres=480 -d guest_errors,unimp -serial stdio -drive file=filename,if=sd,format=raw -device usb-kbd -device usb-mouse -semihosting

this should be a super obscure linking problem, I'm really lost

I can provide the entire project if needed

Thanks a lot,
Valerio

**Comment by smuehlst** [comment]
Are you using the modified QEMU built from https://github.com/smuehlst/qemu?

**Comment by Valefungo** [comment]
> Are you using the modified QEMU built from https://github.com/smuehlst/qemu?

yes, I built it when it was on branch origin/circle-hcd-dwc2, now switched to circle-hcd-dwc2-9.1.1 and rebuilding it, will let you know

**Comment by Valefungo** [comment]
> Are you using the modified QEMU built from https://github.com/smuehlst/qemu?

no, even 9.1.1 behaves identical :(

can you try this kernel8 ?
[nonworking.zip](https://github.com/user-attachments/files/18251452/nonworking.zip)

**Comment by rsta2** [comment]
I did some debugging on your kernel and it turned out, that you have large static data areas in your program, larger than a circle-stdlib program can handle by default. Can you please add the option `-o KERNEL_MAX_SIZE=0x800000`, when calling `configure`, before building circle-stdlib. This allows code and static data to be 8 MBytes large, which should be enough for your application.

**Comment by Valefungo** [comment]
Wow!
that made it!

I would have never found that :)

by the way to make the entire program run I had to add another hex zero so allowing up to 128 megs

Thank you very much

**Comment by Valefungo** [comment]
> I did some debugging on your kernel and it turned out, that you have large static data areas in your program, larger than a circle-stdlib program can handle by default. Can you please add the option `-o KERNEL_MAX_SIZE=0x800000`, when calling `configure`, before building circle-stdlib. This allows code and static data to be 8 MBytes large, which should be enough for your application.

sorry to bother you again... how did you debug this kind of things?

I'm now at the point where it is actually starting my program but it stops literally in the middle of a printf

tried to start qemu with -s -S to stop it waiting for gdb, then attached to it with "target remote localhost:1234" and continued with "c" just to end with a lone "[Inferior 1 (process 1) exited with code 01]"
no logs from qemu or signs from whatever else was running, just "exited normally"

**Comment by rsta2** [comment]
You are welcome. Starting QEMU with -s -S should be OK. GDB can be started 
with "gdb kernel8.elf" and then "target extended-remote :1234".

If you configure circle-stdlib with the -d option and use the -semihosting 
option of QEMU, it is finished, when the application halts (e.g. when an 
assertion fails). You can tried without these options and attach a VNC tool to 
QEMU (port 5900) to see the display output. Perhaps you can see some log 
message there.

**Comment by Valefungo** [comment]
> target extended-remote :1234

I would like to share this with you because it's both making me cry and laugh:

**on qemu side**
fungostar@FungoLinux:~/baremetal$ ./qemu/build/qemu-system-aarch64 -M raspi3b -no-shutdown -action reboot=reset -action shutdown=pause -action panic=pause -action watchdog=pause -kernel circle-stdlib/samples/22-stdio-hello/kernel8.img -global bcm2835-fb.xres=640 -global bcm2835-fb.yres=480 -d guest_errors,unimp -serial stdio -drive file=filename,if=sd,format=raw -device usb-kbd -device usb-mouse -semihosting -s -S
bcm2835_property: unhandled tag 0x00048020
bcm2835_property: unhandled tag 0x00040010
SD: Optional CMD5 not implemented
dwc2_glbreg_write: Core soft reset not implemented
dwc2_glbreg_write: Tx FIFO flush not implemented
dwc2_glbreg_write: Rx FIFO flush not implemented
dwc2_hreg0_write: write to read-only register (this line is repeated thousand times)

**on gdb side**
fungostar@FungoLinux:~/baremetal/circle-stdlib/samples/22-stdio-hello$ aarch64-none-elf-gdb kernel8.elf 
GNU gdb (Arm GNU Toolchain 14.2.Rel1 (Build arm-14.52)) 15.2.90.20241130-git
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "--host=x86_64-pc-linux-gnu --target=aarch64-none-elf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.linaro.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from kernel8.elf...
(gdb) target extended-remote :1234
Remote debugging using :1234
0x0000000000000000 in ?? ()
(gdb) c
Continuing.
[Inferior 1 (process 1) exited with code 01]
Remote communication error.  Target disconnected: error while writing: Broken pipe.

and on my program side... nothing, just my last printf
watch the attached video at 10% of speed because qemu closes so fast that it's impossible to read the screen without screen recording

I'll keep filling it with printf line by line :)

Thank you again for all your support!

https://github.com/user-attachments/assets/db3f0c10-8944-4778-93c2-03c7c9972625

**Comment by Valefungo** [comment]
![immagine](https://github.com/user-attachments/assets/34beb9d6-a176-4577-93ed-fe5043620462)

another run, this was the last frame before vanishing
any clue ?

**Comment by Valefungo** [comment]
Obviously it's my fault 🥇 

Cheers and Thanks again!

**Comment by rsta2** [comment]
So when the issue is solved, it can be closed. You are welcome.

**Comment by Valefungo** [comment]
Just to let you @smuehlst and @rsta2 know, I'm nearly done

![immagine](https://github.com/user-attachments/assets/597f4721-36db-4d28-b0e9-7626d66a25c0)

You both are Top 💯
